temp/unpackaged/objects/Account.object
<CustomObject>
    <fields>
        <fullName>AddressDiscrepancy__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Address Discrepancy</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>AlternativeAddress__c</fullName>
        <label>Alternative Address</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AlternativeCity__c</fullName>
        <label>Alternative City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AlternativePostalCode__c</fullName>
        <label>Alternative Postal Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AlternativeState__c</fullName>
        <label>Alternative State</label>
        <length>15</length>
        <type>Text</type>
    </fields>
</CustomObject>

temp/unpackaged/objects/webServiceConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>custom setting responsible to handle information for Web Services</description>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>end_point__c</fullName>
        <description>endPoint to web services calls</description>
        <label>End Point</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>format__c</fullName>
        <defaultValue>&apos;JSON&apos;</defaultValue>
        <description>format to return from web services calls</description>
        <label>Format</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Web Service Config</label>
</CustomObject>

temp/unpackaged/classes/AccountWebServiceHelper.cls
public class AccountWebServiceHelper {
    
    public static webServiceConfig__c getWebServiceConfig(String configName){
        return [SELECT Id,end_point__c,format__c FROM webServiceConfig__c WHERE Service_Name__c = :configName];   
    }
    
    public static Account updateAccountAddress(Account acc, Address address){
        
        if(address.erro!=null) throw new AccountWebServiceException(Label.invalid_postal_code);
        
        if( (!String.valueof(acc.BillingState).equalsIgnoreCase(address.uf)) 
            || (!String.valueOf(acc.BillingStreet).equalsIgnoreCase(address.logradouro)) 
            || (!String.valueof(acc.BillingCity).equalsIgnoreCase(address.localidade)) )
        {
            acc.AlternativePostalCode__c = address.cep;
            acc.AlternativeState__c = address.uf;
            acc.AlternativeAddress__c = address.logradouro;
            acc.AlternativeCity__c = address.localidade;
            acc.AddressDiscrepancy__c = true;
        }
        
        return acc;
    }
    
    //inner class 
    public class Address{
        public String erro;
        public String cep;
        public String logradouro;
        public String complemento;
        public String bairro;
        public String localidade;
        public String uf;
        public String unidade;
        public String ibge;
        public String gia;
    }
}