temp/unpackaged/objects/webServiceConfig__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>custom setting responsible to handle information for Web Services</description>
    <fields>
        <fullName>Service_Name__c</fullName>
        <label>Service Name</label>
        <length>20</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>end_point__c</fullName>
        <description>endPoint to web services calls</description>
        <label>End Point</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>format__c</fullName>
        <defaultValue>&apos;JSON&apos;</defaultValue>
        <description>format to return from web services calls</description>
        <label>Format</label>
        <length>8</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Web Service Config</label>
</CustomObject>

temp/unpackaged/classes/WSConfigTestData.cls
@isTest
public class WSConfigTestData extends SObjectTestData {
    
    protected override Map<Schema.SObjectField, Object> getDefaultValueMap() {
        return new Map<Schema.SObjectField, Object>{
            webServiceConfig__c.end_point__c => 'http://teste.com.br/ws/',
            webServiceConfig__c.format__c => 'json',
            webServiceConfig__c.Service_Name__c => 'teste'
        };
    }
    
    protected override Schema.SObjectType getSObjectType() {
        return webServiceConfig__c.SObjectType;
    }
    
    public WSConfigTestData withServiceName(String nameService){
        return (WSConfigTestData)super.withDynamicData(webServiceConfig__c.Service_Name__c, nameService);   
    }
    public WSConfigTestData withEndPoint(String endPoint){
        return (WSConfigTestData)super.withDynamicData(webServiceConfig__c.end_point__c, endPoint);      
    }
    public WSConfigTestData withFormat(String format){
        return (WSConfigTestData)super.withDynamicData(webServiceConfig__c.format__c, format);          
    }
    public webServiceConfig__c insertWSConfig(){
        return (webServiceConfig__c)super.insertRecord();
    }
    
    public static WSConfigTestData instance {
        get {
            if (instance == null) instance = new WSConfigTestData();
            
            return instance;
        }
    }
    /**
    * @description Private constructor for singleton.
    */
    private WSConfigTestData() {
        super();
    }
}